buzzwords = {1 : "Männer",
             2 : "Frauen",
             3 : "Dating",
             4 : "das Internet",
             5 : "Veganismus",
             6 : "Liebe",
             7 : "Wetter",
             8 : "Kinder",
             9 : "Geld",
             10 : "Tod"}

greetings = {1 : "Guten Abend [P]!",
             2 : "Hallo Liebe Menschen in [P]!",
             3 : "[P] seid ihr gut drauf?!",
             4 : "Hallo. Rufe GPS-Daten ab. [P].",
             5 : "Hey ich habe gehört es gibt nur schöne Menschen in [P]"}

setups ={1 : "Habt ihr schon gehört?!: ",
         2 : "Und letztens, kannst du dir nicht ausdenken, heißt es: ",
         3 : "Ich hab letztens gelesen: ",
         4 : "Wirklich wahr! Jetzt heißt es auf einmal überall: ",
         5 : "Ich hab mich letztens schon wieder aufgeregt: ",
         6 : "Da schlag ich letztens die Zeitung auf und was muss ich lesen?",
         7 : "Und dann hieß es auch noch neulich: "}

punchlines = {1 : "Wenn ich das schon höre: \'[NN]!\'",
              2 : "Junge, Meine Oma ist so alt, selbst die kannte schon [NN].",
              3 : "[NN] macht Kinder froh und Erwachsene ebenso!",
              4 : "Ich kannte mal wen, der immer von [NN] geredet hat. Ich sag mal so: wir reden nicht mehr miteinander.",
              5 : "Da frag ich mich: haben die noch alle Latten am Zaun?",
              6 : "[NN] soweit kommts noch!",
              7 : "Bis ich [NN] gut finde, friert die Hölle zu, Liebe Leute!",
              8 : "Kennt ihr [NN]? Kennt ihr, kennt ihr??",
              9 : "Da frag ich mich doch: wen wollen die eigentlich verarschen?",
              10 : "Ich sag ja immer: wer [NN] nicht ehrt ist es auch nicht wert.",
              11 : "Wie heißt es noch so schön? Wer [NN] nicht ehrt, den tritt ein Pferd?",
              12 : "Kann mir einer mal erklären, was das sein soll? [NN]?? Das checkt doch kein normaler Mensch mehr, was die damit meinen!",
              13 : "Von wegen [NN]. Ich hätte da ganz andere Sachen im Sinn, wenn ihr versteht, was ich meine.",
              14 : "Wenn ich [NN] will, kann ich auch gleich zu Hause bleiben.",
              15 : "Wenn du [NN] willst, musst du nur das Fenster aufmachen.",
              16 : "Haben Sie mal irgendetwas sinnvolles über [NN] gehört? Ich auch nicht.",
              17 : "Und da frag ich mich: [NN], wen interessiert das denn bitte noch?",
              18 : "[NN], [NN], [NN] - ich kanns nicht mehr hören!",
              19 : "[NN] kenn ich noch aus meiner Kindheit und das war damals schon scheiße.",
              20 : "[NN], damit ist ja schon alles gesagt.",
              21 : "Ey komm mir nicht mit [NN].",
              22 : "Das sagen die tatsächlich so: \'[NN]\'.",
              23 : "Also ich kann mich gut erinnern, dass wir früher auch ohne [NN] ausgekommen sind.",
              24 : "[NN] hab ich zu Hause!",
              25 : "Was soll das?",
              26 : "Unsere Freiheit ist bedroht und die reden immer noch von [NN], das kanns doch nicht sein!",
              27 : "Man muss sich ja nur einmal fragen, wem [NN] nützt. Da kommt man recht schnell drauf, dass das Käse ist!",
              28 : "Dass ich nicht lache. Jetzt soll mir noch einer mal kommen und was von [NN] erzählen.",
              29 : "Also, wer jetzt noch von [NN] spricht, dem ist auch nicht mehr zu helfen.",
              30 : "Früher, also früher, da gab's das klar! Aber [NN] von heute hat damit doch nichts mehr zu tun.",
              31 : "[NN]? Da gibt es doch bestimmt Tabletten gegen, oder?",
              32 : "Ich will ja nichts sagen, aber ich glaube, das hätte man ahnen können, wenn es um [NN] geht.",
              33 : "Mich überrascht da gar nichts mehr. Wenn die da oben [NN] wollen, dann kriegen sie auch [NN].",
              34 : "Aber, vorsicht! [NN] ist ja nicht gleich [NN].",
              35 : "Ja, wenn du über [NN] redest, kannst du ja auch gleich über [A] reden!",
              36 : "Boah, stell dir das mal vor! Da bestellst du [NN], bekommst aber [A]. Also ich wäre sauer!",
              37 : "[NN] haben die gesagt! Wirklich war und da dachte ich mir: das kenne ich doch! Aber früher hieß das bei uns [A].",
              38 : "[NN], [NN], wenn ich das schon höre! Sag doch einfach [A] und gut ist!",
              39 : "Ja, Sie lachen! Aber alle reden immer von [NN] aber niemand. Wirklich niemand spricht von [A].",
              40 : "Also wenn deine größte Sorge [NN] ist, kannst du gleich nach Hause gehen.",
              41 : "Oho die feinen Menschen haben also endlich [NN] entdeckt. Bravo!",
              42 : "Mal unter uns: wer von euch kennt sich überhaupt mit [NN] aus? Also ich nicht.",
              43 : "Bruder, komm mir noch einmal mit [NN]. Ich schwöre ich mach bald ein Rapalbum als MC [NN].",
              44 : "Hört her, hört her es geht mal wieder um [NN].",
              55 : "Dass ich nicht lache.",
              56 : "Ja, schieß mir ins Bein und nenn mich Jürgen, \'[NN]\', das ist doch nicht mehr normal!",
              57 : "Ich sage euch, bald dreh ich durch.",
              58 : "Kennt ihr das auch?",
              59 : "Immer, wenn jemand [NN] sagt zieht sich in mir etwas zusammen.",
              60 : "Hahahaha, [NN]!!",
              61 : "Da weiß man auch nicht, ob man lachen oder weinen soll."}

#NT = New Topic, OT = Old Topic

transitions = {1 : "Wo wir gerade schon bei [NT] sind!",
               2 : "Thema [NT].",
               3 : "Appropos [NT].",
               4 : "Wo wir gerade über [NT] sprechen.",
               5 : "Aber genug von [OT], lasst uns mal kurz über das Thema [NT] sprechen?!",
               6 : "Anderes Thema: [NT].",
               7 : "Aber was erzähle ich euch von [OT], wir alle wollen über eine Sache sprechen und das ist - na klar: [NT].",
               8 : "Ihr kennt doch sicher [NT].",
               9 : "Okay, aber nun mal zu einem Thema, das mir wirklich am Herzen liegt. Etwas, wo in unserer Gesellschaft zu wenig drüber gesprochen wird: [NT].",
               10 : "Aber man kann ja nicht über [OT] sprechen, ohne über [NT] zu sprechen!"}



endings = {1 : "[P], ihr wart wunderbar!",
           2 : "Das war's von mir, ciao!",
           3 : "Danke, ihr wart ein Publikum.",
           4 : "Vielen Dank, das wars!",
           5 : "Aber naja. Liebe Menschen in [P], das war's von mir!"}